services:
  # FastAPI Backend
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: autoaudit-server
    expose:
      - "8000"
    environment:
      - ENVIRONMENT=production
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_PATH=/app/data/compliance.db
      - CORS_ORIGINS=${CORS_ORIGINS}
    volumes:
      # Persist database
      - ./server/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - autoaudit-network

  # React Frontend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=
    container_name: autoaudit-client
    expose:
      - "80"
    depends_on:
      - server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - autoaudit-network

  # NGINX Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: autoaudit-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
      - client
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - autoaudit-network

volumes:
  database:
    driver: local

networks:
  autoaudit-network:
    driver: bridge
